/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#include <stdlib.h>
#include<stdio.h>
#include "memorymap.h"

void clock_init()
{
	//	Bit 2 IOPAEN: I/O port A clock enable
	//	Set and cleared by software.
	//	0: I/O port A clock disabled
	//	1:I/O port A clock enabled

	//ENABLE CLOCK GPIOA
	RCC_ABP2ENR |= RCC_IOPAEN;


	//	Bit 3 IOPBEN: I/O port B clock enable
	//	Set and cleared by software.
	//	0: I/O port B clock disabled
	//	1:I/O port B clock enabled

	//ENABLE CLOCK GPIOB BIT 3
	RCC_ABP2ENR |= (1<<3);
}

void GPIO_init()
{
	GPIOA_CRL=0 ;
	GPIOA_CRH =0 ;
	GPIOA_ODR =0 ;


	//PORT A PIN 1
	//	00: Input mode (reset state)
	GPIOA_CRL &= ~(0b11<<4);
	//	01: Floating input (reset state)
	GPIOA_CRL |= (0b01<<6);

	//PORT A PIN 13
	//	00: Input mode (reset state)
	GPIOA_CRH &= ~(0b11<<20);
	//	01: Floating input (reset state)
	GPIOA_CRH |= (0b01<<22);

	//PORT B PIN 1
	//	01: Output mode, max speed 10 MHz.
	GPIOB_CRL |= (0b01<<4);
	//	00: General purpose output push-pull
	GPIOB_CRL &= ~(0b11<<6);

	//PORT B PIN 13
	//	01: Output mode, max speed 10 MHz.
	GPIOB_CRH |= (0b01<<20);
	//	00: General purpose output push-pull
	GPIOB_CRH &= ~(0b11<<22);

}

void wait_ms(uint32_t time){
	uint32_t i,j ;
	for(i=0 ;i<time;i++)
		for(j=0;j<255;j++);
}


int main(void)
{
	clock_init();
	GPIO_init();

	while(1)
	{
		if (((GPIOA_IDR&(1<<1)) >>1 )==0)
		{
			GPIOB_ODR ^= 1<<1 ;
			while ((((GPIOA_IDR &(1<<1)) >>1)==0)) ; //SINGLE PRESSING
		}
		if (((GPIOA_IDR&(1<<13)) >>13 )==1)
		{
			GPIOB_ODR ^= 1<<13 ;

		}
		wait_ms(1);
	}
}
